### ISSUE TITLE
Support GNOME 40

### ISSUE THREAD

**Issue by gavr123456789** [paperwm/PaperWM#376]

**Comment by mrspikeroot** [comment]
GNOME put out this info for extension developers
https://blogs.gnome.org/shell-dev/2021/03/20/extensions-rebooted-porting-your-existing-extensions-to-gnome-40/

**Comment by hedning** [comment]
Have` started working on support for gnome shell 40 here: https://github.com/paperwm/PaperWM/tree/next-release

Things should start and launching windows should work, but there's quite a few bugs (eg. scrolling the workspaces seems to crash the process, and dragging windows are broken).

**Comment by qwIvan** [comment]
> Have` started working on support for gnome shell 40 here: https://github.com/paperwm/PaperWM/tree/next-release
> 
> Things should start and launching windows should work, but there's quite a few bugs (eg. scrolling the workspaces seems to crash the process, and dragging windows are broken).

The configuration panel doesn't works now. How can I modify the configuration manually?

**Comment by wbolster** [comment]
using dconf-editor, orn using the gsettings command line tool. you can check my wbolster/dotfiles repo (gnome subdirectory) for some examples

**Comment by qwIvan** [comment]
> using dconf-editor, orn using the gsettings command line tool. you can check my wbolster/dotfiles repo (gnome subdirectory) for some examples

Animation of switch focus between two monitor is incorrect. How to disable animation?

**Comment by qwIvan** [comment]
> using dconf-editor, orn using the gsettings command line tool. you can check my wbolster/dotfiles repo (gnome subdirectory) for some examples

![image](https://user-images.githubusercontent.com/7613160/113989011-99e4a100-9882-11eb-94be-556215f7cfdd.png)
The above command is refer from your dotfile, but it doesn't work.

**Comment by wbolster** [comment]
ah yes, this extension's name is problematic because it contains a `:` (colon), which the `gsettings` tool treats as a path separator (`GSETTINGS_SCHEMA_DIR`). i reported this before in #322.

i use an ugly symlink based hack to work around it:

```
    # HACK: The colon in the name confuses the GSETTINGS_SCHEMA_DIR
    # environment variable used by the ‘gsettings’ tool, so trick
    # it into picking up the right directory anyway.
    ln -s 'paperwm@hedning:matrix.org/schemas' 'paperwm@hedning'
```

see https://github.com/wbolster/dotfiles/blob/main/gnome/install-extensions#L39-L42

**Comment by qwIvan** [comment]
I found a solution to disable the incorrect animation. Just open `gnome-teaks` and disable the animation option.

**Comment by gavr123456789** [comment]
Cant enable now  
![image](https://user-images.githubusercontent.com/30507409/115521012-63038780-a293-11eb-81e6-f3e78fbbce00.png)

**Comment by KiaraGrouwstra** [comment]
> after alt + f2 -> r It started working
this gives me: restart is not available on Wayland
😅  reboots have not fixed tho...

**Comment by nylki** [comment]
Btw. the Gnome Foundation put up a migration guide from GTK3->GTK4, if you haven't come across this one, this may be useful:
https://developer.gnome.org/gtk4/4.0/gtk-migrating-3-to-4.html

**Comment by ludvigng** [comment]
Just a heads up, currently this extension breaks the overview, no windows will be shown. It's probably already known I'm guessing, but might as well mention it.

**Comment by Thesola10** [comment]
> Just a heads up, currently this extension breaks the overview, no windows will be shown. It's probably already known I'm guessing, but might as well mention it.

To me it looks more like the "show only scratch windows in overview" setting working as intended

**Comment by ludvigng** [comment]
> > Just a heads up, currently this extension breaks the overview, no windows will be shown. It's probably already known I'm guessing, but might as well mention it.
> 
> To me it looks more like the "show only scratch windows in overview" setting working as intended

Except I don't have that set. And scratch windows aren't shown either.

https://user-images.githubusercontent.com/50339757/116528427-1d227100-a8dc-11eb-98f4-7d245e4b1fc2.mp4

I did notice something else strange too. Moving the cursor between monitors makes for a really jarring animation (I set OBS to record half of each screen, the seam is in the middle between them):

https://user-images.githubusercontent.com/50339757/116528549-404d2080-a8dc-11eb-9bb0-4815951b2ad5.mp4

This is with "Workspaces span displays" set in gnome tweaks.


There's also another bug I have with the overview where it just becomes a big gray screen with a text input. From here I can launch apps, but they'll be launched behind the overview and I can't exit it at all until I restart the shell with alt+f2, r. However, I haven't managed to get it to happen consistently yet, so I can't say for sure if it's a problem with paperWM or not yet.

**Comment by HarunOr** [comment]
I get this error while installing: 

```
Enable the extension [Y/n]? Y
Trying to load and enable extension:
something went wrong:
Missing metadata.json createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:283:19\
@resource:///org/gnome/shell/ui/shellDBus.js line 63 > eval:20:36\
Eval@resource:///org/gnome/shell/ui/shellDBus.js:63:42\
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:310:38\
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34\
"')
Success
```
Does anyone have an idea how to fix this?

**Comment by gcoda** [comment]
> Just a heads up, currently this extension breaks the overview, no windows will be shown. It's probably already known I'm guessing, but might as well mention it.

for me, it magically got fixed with "Cleaner Overview" extension by gonza_11

**Comment by ludvigng** [comment]
> > Just a heads up, currently this extension breaks the overview, no windows will be shown. It's probably already known I'm guessing, but might as well mention it.
> 
> for me, it magically got fixed with "Cleaner Overview" extension by gonza_11

Oh wow, it does fix the problem. Thank you!

**Comment by nylki** [comment]
I can confirm that, using the mentioned [Cleaner Overview](https://extensions.gnome.org/extension/3759/cleaner-overview/) fixes the empty overview. Maybe some of that extensions logic can be adapted for PaperWM.

there is another gesture-related issue: When switching windows with the 3-finger gesture as before with PaperWM now clashes with Gnome-40's 3-finger worksapce switching gesture.
Using the Meta-left/right key-combo does work fine though.

**Comment by magthe** [comment]
I'm testing the `next-release` branch right now with Gnome40 on Arch.

I do have the Cleaner Overview plugin, but I still have an empty overview. Maybe there's some other extension I have that impacts my setup negatively.

The plugin [ddterm](https://extensions.gnome.org/extension/3780/ddterm/) still doesn't show its window, but it does take focus!

**Comment by randomvariable** [comment]
How have folk got around
> `Expected type string for argument 'property_name' but got type GObject_Object`

**Comment by Pacman99** [comment]
Also enabling the built-in extension "Native Window Placement" fixes the empty overview.

> Expected type string for argument 'property_name' but got type GObject_Object

I'm getting this too

**Comment by Pacman99** [comment]
Overall `release-next` works pretty well thank you for all the work with that.
The animations are definitely a bit odd with the switch to horizontal workspaces.

Also the paperwm settings gui doesn't open at all and changing some top-level settings in dconf seems to just crash gnome. But logging out and logging in seems to fix the crash. So applying paperwm settings requires a restart of gnome. Changing keybindings works fine.

**Comment by paradajz** [comment]
Some of my observations after trying `next-release` branch on GNOME 40 (openSUSE Tumbleweed, Wayland on a laptop)

1) Extension installs and loads fine, although settings can't the changed through GUI
2) Extension is fighting with the new, built in gestures. This makes it unusable on laptop unless the gestures are changed to 4-finger swipes. See https://github.com/icedman/gnome-shell-hammer
3) Resizing the windows works with keyboard shortcuts and with mouse, however windows can't be dragged at all.
4) Overview shows no windows unless Cleaner Overview is installed. https://extensions.gnome.org/extension/3759/cleaner-overview/
5) Animations when switching from overview are kind of broken, but then again, they are kind of broken on 3.38 as well. See https://github.com/paperwm/PaperWM/issues/347

This is actually workable on a laptop, but still unusable for me on a desktop due to broken window movement. I really hope development of this extension isn't abandoned, I'd hate to switch to something else.

**Comment by tomkdale** [comment]
I have two machines running Fedora 34, I've installed the "Native Window Placement", and "Cleaner Overview" extensions on both. Yet when I go to install `next-release` paperwm on both, one works fine, but the other always gives me the `Expected type string for argument 'property_name' but got type GObject_Object` error.

**Comment by Tina-otoge** [comment]
I tried to use [`next-release`](/paperwm/PaperWM/tree/next-release) on GNOME 40 but I had a lot of issue with my dual monitor setup.
I wasn't able to get PaperWM to "snap" windows in the second display, I could only move and resize them the regular GNOME way, moving between windows on my first monitor using Super+arrow keys works fine but using Super+1,2,3,4 shortcuts made them overlap on the second monitor and breaking them out of PaperWM control
Switching workspaces plays a vertical transition animation, and then when it ends perform the new GNOME 40 horizontal scrolling animation, making it very weird
And generally same issues as mentioned by [paradajz right above](#issuecomment-849563269), with not being able to go in the extensions configuration GUI being a major pain.

**Comment by ludvigng** [comment]
You can "fix" the snapping by making workspaces span displays in gnome-tweaks in multi-monitor setup. It works a little funny, since the second monitor uses the second workspace, but it kinda works once you get used to it.

**Comment by cstich** [comment]
I can't seem to get the `next-release` branch to work at all. I am on Gnome 40 on Nixos 21.05. The error message I get when trying to use `install.sh` is this one: 

````
Trying to load and enable extension:
something went wrong:
Missing metadata.json createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:283:19\
@resource:///org/gnome/shell/ui/shellDBus.js line 63 > eval:20:36\
Eval@resource:///org/gnome/shell/ui/shellDBus.js:63:42\
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:310:38\
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:387:34\
"')
````

Does anyone know how to fix this/a workaround?

**Comment by NelsonJeppesen** [comment]
I've been running PapperWM full-time on Gnome 40 (NixOS) for about a week now. Everything works as I expect, without any issues.

For anyone wanting to test this in NixOS, I added this overlay to home-manager to switch branch
https://github.com/NelsonJeppesen/nix-lifestyle/blob/main/nixpkgs/overlays/paperwm.nix

**Comment by magthe** [comment]
Reading all of the above has prompted me to try the branch `next-release` a bit more seriously this time.

The one thing in my setup that doesn't work is [ddterm](https://extensions.gnome.org/extension/3780/ddterm/). There are some visual cues making me think that the shortcut for it works, but the terminal window itself doesn't appear. I'm not sure where the issue is, and I don't know how to find out. Suggestions for how to track down the cause of this would be very welcome.

**Comment by heyarne** [comment]
@NelsonJeppesen Thanks for creating the Overlay! I just switched to NixOS 21.05 w/ Gnome 40. I'm unfortunately also getting
```
Expected type string for argument 'property_name' but got type GObject_Object
```
and can't enable PaperWM in Extensions.

I don't have any other extensions installed, the only other extension that I have enabled is the removable drive menu. This is the config I'm using in addition to the provided overlay:
```
{ config, pkgs, ... }:
{
  home.packages = with pkgs; [
    gnomeExtensions.paperwm
    gnome.gnome-tweak-tool
    gnome.sushi
    adapta-gtk-theme
    arc-theme
    paper-icon-theme
    papirus-icon-theme

    noto-fonts-cjk
  ];
}
```

**Comment by KiaraGrouwstra** [comment]
> Expected type string for argument 'property_name' but got type GObject_Object

I'm getting a similar error on Arch

**Comment by randomvariable** [comment]
For those getting the error
> Expected type string for argument 'property_name' but got type GObject_Object

this is a complete hack, which is why I'm not PR'ing it, but you can change extension.js as follows

```patch
From 10d55747d353c9b2db4df46ded931718773a059f Mon Sep 17 00:00:00 2001
From: Naadir Jeewa <naadir@randomvariable.co.uk>
Date: Fri, 25 Jun 2021 10:40:12 +0100
Subject: [PATCH] This is a hack

---
 extension.js | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/extension.js b/extension.js
index ceda859..90da7bb 100644
--- a/extension.js
+++ b/extension.js
@@ -194,7 +194,7 @@ function notify(msg, details, params) {
     Main.messageTray.add(source);
     let notification = new MessageTray.Notification(source, msg, details, params);
     notification.setResident(true); // Usually more annoying that the notification disappear than not
-    source.notify(notification);
+    source.notify(msg);
     return notification;
 }
 
-- 
2.31.1
```

**Comment by magthe** [comment]
I'm seeing the occasional gnome crash/restart on starting a new app. So far it's been Zoom and Slack causing it. I'm not sure where I can catch some sort of error log to get some indication of what might cause it. Pointers are very welcome.

**Comment by cstich** [comment]
@magthe Have you had a look at `journalctl` yet? Something like `journalctl _UID=1000` (your UID might be different though) should give you the log of the all processes you started.

**Comment by magthe** [comment]
@cstich no, didn't think of that. I'll make sure to keep it in mind the next time Gnome dies on me.

**Comment by magthe** [comment]
This morning Zoom crashed Gnome for me again, actually several times and I ended up switching from PaperWM just to be able to work. I did catch the logs using `journalctl _UID=1000` after the first time. The logs can be found at https://termbin.com/afu4

I logged in 08:49:28 and the crash happened around 10:13.

Hopefully the logs can offer some indication of what the underlying issue is.

**Comment by magthe** [comment]
[paperwm-crash.txt](https://github.com/paperwm/PaperWM/files/6725641/paperwm-crash.txt)

**Comment by magthe** [comment]
I decided to make one more attempt, but this time I turned off Wayland, and so far it's been more stable. No crash for the entire day so far. (I just hope I don't jinx it now :) )

**Comment by michaelhthomas** [comment]
Using the following array of extensions makes PaperWM much more usable on Gnome 40, and essentially brings back normal behavior:

- [Cleaner Overview](https://extensions.gnome.org/extension/3759/cleaner-overview/)
- [Vertical overview](https://extensions.gnome.org/extension/4144/vertical-overview/)
- [Disable Workspace Switch Animation for GNOME 40+](https://extensions.gnome.org/extension/4290/disable-workspace-switch-animation-for-gnome-40/)

These extensions bring back proper vertical workspace navigation and also remove glitches in the overview and in navigation animations between workspaces. I'm currently using the overlay by @NelsonJeppesen on NixOS, thanks for that!

**Comment by gatlee** [comment]
```
gnomeExtensions.cleaner-overview
gnomeExtensions.vertical-overview
gnomeExtensions.disable-workspace-switch-animation-for-gnome-40
```
The packages @michaelhthomas mentioned, for the lazy :)

**Comment by raiguard** [comment]
Just wanted to pop in and say that PaperWM on Gnome 40 has worked pretty OK for me so far. I can't open the settings GUI, but luckily I already have it configured just how I want. The only other glitch I've been experiencing is that when switching workspaces, all of the workspaces are dimmed.

Unfortunately, I can't get a screenshot because it requires holding super.

**Comment by gcoda** [comment]
@raiguard its new gnome animation, they should fade from black, there is extension for disabling workspace switching animation but it did not work for me. i am just using using [Workspace Switch Wraparound](https://github.com/theychx/WorkspaceSwitcherWrapAround) extension, and native gnome keybinding for workspace switching. 

For some reason there is no Up and Down in Settings app.
Manually editing `switch-to-workspace-down` in `dconf-editor /org/gnome/desktop/wm/keybindings` works.

There is also [Vertical Overview](https://github.com/RensAlthuis/vertical-overview) extension for consistency in overview

And you could also edit PaperWM settings with `dconf-editor /org/gnome/shell/extensions/paperwm/`

![image](https://user-images.githubusercontent.com/556999/126856607-9eaca121-17e0-4649-9f14-c83bdaaf3962.png)

**Comment by raiguard** [comment]
@gcoda Thanks for your tips. I was already using `disable workspace switching animation`, but as you said, it doesn't fix the dimming. It does fix the monitor seizure when moving windows between monitors though, which is much more important.

As for the activities overview, I avoid it entirely. I find it utterly useless for my workflow, so I actually completely avoid it and the app grid by using ArcMenu as a launcher. This way I don't have to worry about seeing the default background at any point in my workflow (I use different wallpapers per workspace).

![image](https://user-images.githubusercontent.com/3515394/126881061-9b07c0db-b3d1-446f-9fd2-577b53ccf14b.png)

Somewhat unrelated: Can I entirely hide PaperWM's activities button (the button that usually shows the workspace name)? I disabled the workspace names, but that changed the button to say Activities, and regular "hide activities button" extensions don't work here.

**Comment by adamlwgriffiths** [comment]
Just wanted to summarise the current state of this issue.
Confirmed that this works in in Gnome 40 with the `next-release` branch (running NixOS 21.05).

Summary of changes required:
* use the `next-release` branch
  * using the nix configs provided above ([my overlay](https://github.com/adamlwgriffiths/nix-configs/blob/master/home-manager/overlays/paperwm.nix)),
* delete `~/.config/paperwm/user.js`
  * without deleting this you cannot enable the plugin as you get the `Expected type string for argument 'property_name' but got type GObject_Object` error in Gnome Extensions.

The only functionality I've seen that isn't working:
* the paperwm settings dialog doesn't appear when clicked in tweaks (mentioned above).
* you cannot drag windows left or right, the mouse cursor changes but nothing happens (also mentioned above). specifically:
  * you can use the key commands to swap windows
  * you can click to change windows or click the edge to scroll
  * you _cannot_ perform fine adjustment by dragging the title bar

There is another gnome-ism which deviates from the Gnome 39 behaviour, which im not sure is paperwm.
When you login, you initially are presented with the zoomed out workspace switcher.

**Comment by magthe** [comment]
There's also something wonky with the scratch layer as opening applications configured to start on the scratch layer sometimes crashes the shell. When the shell restarts _all_ applications are "tiled".

**Comment by paradajz** [comment]
Anyone tried PaperWM on GNOME 41?

@hedning is this extension abandoned?

**Comment by paradajz** [comment]
Was trying it out on GNOME 41. Works mostly the same as in GNOME 40, with the added annoyance that opening new windows sometimes results in glitchy animation. `metadata.json` needs to be modified by adding `41` to supported GNOME versions. Cleaner overview officially isn't compatible with GNOME 41 as well, meaning no windows in overview, but, same hack can be applied - just add `41` to its `metadata.json` file and it works

**Comment by randomvariable** [comment]
I've just done a fresh Fedora 35 beta install, and it looks like most of the dconf settings are missing, such that the keybindings can't be set.

**Comment by soraxas** [comment]
Hi all! I'm not sure if this is common or not, but ever since switching to the GNOME 40 branch, the scratch layer had been a bit funky to me. It works well when manually switching a window with the key shortcut `Super + Escape`.

However, when using the pref file in `~/.config/paperwm/user.js` to automatically place window to scratch (via matching `wm_clas` or `wm_title`), it **sometimes** crashes my window manager (and then after crashing gnome restarts the wm).

The journalctl log looks like:
```
Nov 08 10:12:03 manjaro audit[1299]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=1 subj==unconfined pid=1299 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
Nov 08 10:12:03 manjaro kernel: traps: gnome-shell[1299] general protection fault ip:7f9beea7e5e7 sp:7ffd7e0bea50 error:0 in libmozjs-78.so[7f9bee6a1000+b4c000]
Nov 08 10:12:03 manjaro kernel: audit: type=1701 audit(1636326723.133:488): auid=1000 uid=1000 gid=1000 ses=1 subj==unconfined pid=1299 comm="gnome-shell" exe="/usr/bin/gnome-shell" sig=11 res=1
Nov 08 10:12:03 manjaro audit: BPF prog-id=69 op=LOAD
Nov 08 10:12:03 manjaro audit: BPF prog-id=70 op=LOAD
Nov 08 10:12:03 manjaro audit: BPF prog-id=71 op=LOAD
Nov 08 10:12:03 manjaro systemd[1]: Started Process Core Dump (PID 238474/UID 0).
Nov 08 10:12:03 manjaro audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@10-238474-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? a>
Nov 08 10:12:03 manjaro kernel: audit: type=1334 audit(1636326723.147:489): prog-id=69 op=LOAD
Nov 08 10:12:03 manjaro kernel: audit: type=1334 audit(1636326723.147:490): prog-id=70 op=LOAD
Nov 08 10:12:03 manjaro kernel: audit: type=1334 audit(1636326723.147:491): prog-id=71 op=LOAD
Nov 08 10:12:03 manjaro kernel: audit: type=1130 audit(1636326723.147:492): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@10-238474-0 comm="systemd" exe="/usr/lib/s>
Nov 08 10:12:04 manjaro systemd-coredump[238475]: [🡕] Process 1299 (gnome-shell) of user 1000 dumped core.
                                                      
                                                      Found module linux-vdso.so.1 with build-id: 22c299cd29a55a3d70d5abdd9c15cc65ec4fa843
                                                      Found module libnss_dns.so.2 with build-id: b0d90fd1794c177c70f1e457c11ec1a7f87a41ed
.....
.....
Nov 08 10:12:05 manjaro systemd[1]: systemd-coredump@10-238474-0.service: Deactivated successfully.
Nov 08 10:12:05 manjaro kernel: audit: type=1131 audit(1636326725.040:493): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@10-238474-0 comm="systemd" exe="/usr/lib/s>
Nov 08 10:12:05 manjaro audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@10-238474-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? ad>
Nov 08 10:12:05 manjaro systemd[1]: systemd-coredump@10-238474-0.service: Consumed 1.850s CPU time.
```
It is weird because it does not always crashes (sometimes it was able to place the matched window to scratch). But when it crashes, the **window that is supposed to be matched** will NOT be in the scratch layer (after the wm restarted). And the alternating in-between crash and no crash can happens in consecutive closing and relaunch the same window. 

I suspect this is related to the weird window glitch in GNOME 40 when creating new window that wasn't present in the previous GNOME.

This is a shame because paperwm is such an amazing window manager that I absolutely love using.

**Comment by jsravn** [comment]
@hedning hopefully all is okay! They have not been seen in 8 months so I assume maintenance of paperWM is dead. There are no alternatives sadly as far as I can find, paperWM is pretty unique in the tiling WM landscape.

**Comment by cstich** [comment]
@jsravn The closest alternative I can think of is [Pop Shell](https://github.com/pop-os/shell). Although with system 76 planning to ditch Gnome entirely I am not sure how long they will actually still keep developing that. 

Maybe someone has to fork PaperWM? I have absolutely no idea about either JS nor Gnome development, so I am probably not the right person to lead this but I am happy to help if anyone is working on Gnome 40 support.

**Comment by jsravn** [comment]
I think if I want i3 style tiling I'd just use Sway which I used for a long time before PaperWM. I find paperwm's approach superior on widescreens and large monitors where you can easily center what you're working on. i3 is really painful for this kind of screen, it seems more ideal for laptop screens or smallish < 27" where you have the whole display in your vision.

**Comment by deejayem** [comment]
https://github.com/cardboardwm/cardboard may be a possibility:

"Cardboard is a unique, scrollable tiling Wayland compositor designed with laptops in mind. Based on wlroots...

The idea of scrollable tiling comes from PaperWM."

**Comment by jsravn** [comment]
Cardboard looks pretty cool - however it's in a similar state with an inactive maintainer. I may try giving it a spin though when I get the time.

**Comment by derrix060** [comment]
I was also searching for a similar WM and found https://github.com/material-shell/material-shell.

At least it is still being supported...

**Comment by smichel17** [comment]
<details><summary>First— six or seven months of inactivity does not mean abandoned.</summary>

It might mean that the maintainer is busy with other things, and that maintenance will resume when they are personally affected. For example, I maintain [Red Moon](https://github.com/libreshift/red-moon), currently in [low maintenance mode](https://github.com/LibreShift/red-moon/issues/281), aka maintained to a level of "works for me". 

Red Moon hasn't received a major update in several years and has issues on more recent version of Android. But it's not dead; I still use it daily… I'm just still using a Galaxy S6 running Android 7.0. If I get a new Android phone before switching to a Linux phone, development will start again.

</details>

Material shell is similar but not scrollable, which is really a key difference.

Cardboard's lack of maintenance may not be as much of an issue as PaperWM, because it's a full window manager, rather than an extension on top of Gnome. So, a slow development pace might just mean not getting any new features or bugfixes, whereas running an old version of gnome-shell that still supports PaperWM may become more difficult.

**Comment by derrix060** [comment]
Material Shell does have scrollable, the only difference is that the width is not freely resizable...

**Comment by magthe** [comment]
I started https://gitlab.com/magus/wf-scud after reading one of the cardboard author's blog posts. I've not fully made the switch myself yet but I'm increasing my wayfire usage steadily.

**Comment by hikhvar** [comment]
@smichel17 yes it may not be abandoned, however let's rephrase it. The maintainership is not in a healthy state. In this thread we have the voices of al ot of users. As with most open source projects there are more users than potential developers. Myself is a Javascript and Gnome Shell noob.

**Comment by juanxrv** [comment]
I love PaperWM but sad it's half dead

**Comment by smichel17** [comment]
I noticed from the [network graph](https://github.com/paperwm/PaperWM/network) that @tadfisher, @YannikSc and @Gelbana have all made changes towards Gnome 40/41 support in the last month in their own forks. Maybe we can coordinate a soft fork to make some progress until @hedning gets back?

**Comment by smichel17** [comment]
@olejorgenb What are your permissions on this repo and the @paperwm org? I'd like to be respectful that this is still @hedning's project, but at the same time, it would be most convenient if we didn't have to move far. If you have the right permissions, I was thinking something like creating a new repo under the same org, and adding @tadfisher, @YannikSc, and @Gelbana as collaborators there, if they are interested.

**Comment by KiaraGrouwstra** [comment]
@smichel17 in the event @olejorgenb has indeed been entrusted with the ability to accept PRs here, then might we not as well stay in this repo?

**Comment by smichel17** [comment]
I was envisioning giving all 3 of them push access, so they can merge each other's PRs without being dependent on @olejorgenb's availability, and I wouldn't want to do that on this repo without @hedning's permission. Also, I think it's a good idea to leave the `master`, `develop`, and `next-release` branches as they are, so @hedning can decide how to incorporate the updates. It may be possible to set something like that up on this repo, but I figured it would be easiest just to make a new repo and grant broad permissions (this one can still be used for issue tracking).

**Comment by KiaraGrouwstra** [comment]
perfect, thanks for clarifying!

**Comment by YannikSc** [comment]
Good, that I took a look into this issue, as I missed the GitHub mails. I just checked and noticed, that @Gelbana and I were doing sort-of the same, but luckily not completely the same.
So I merged his changes into my fork for now, mostly because I'm using PaperWM daily and every fix is a good fix.

I wonder if there is a list of bugs focussed on GNOME 40?
I already wrote all problems I found into a `TODOS.md`, which is fine when working alone, but for collaboration we could maybe create gh issues and label them with GNOME 4x?

**Comment by tadfisher** [comment]
I have a GTK 4 prefs UI written, and I'm currently cleaning up the keybindings page. Right now my code makes the extension compatible with Gnome 40+ only, but we could discuss maintaining compatibility with older shell versions. I'm happy to contribute in any way, including starting a new branch (preferably based on `next-release` as that's what my fork is based on).

**Comment by hikhvar** [comment]
As we can't manage to get write access to this repository, is it worth it to create a fork with all write access for those who want to contribute?

**Comment by Gelbana** [comment]
I have just been fixing small issues as I come across them since I still daily drive this extension (honestly don't know if it's possible to live without it on a 32:9 monitor). 
In line with @tadfisher, some of the changes made are not backwards compatible.

If any changes happen to be useful to the project, I am happy to contribute.

**Comment by cstich** [comment]
If we setup a (soft) fork, I'll help out as best as I can as well, which won't be a massive contribution given that I don't know JavaScript.

I was just wondering whether we need to maintain backwards compatibility at all. Everyone stuck on a version before Gnome 40 could just use PaperWM from this repo, no?

**Comment by michaelhthomas** [comment]
Just created an org with a new fork of the main repo ([PaperWM-community/PaperWM](https://github.com/PaperWM-community/PaperWM)), and invited several of you. Let me know if there's anyone else wanting to contribute, I'd be happy to add you on as well. Feel free to add all your existing changes @Gelbana, it's already working great for me!

**Comment by MikulasVanousek** [comment]
So is the fork already compatible with gnome 40? If so, please update the read me and I will test it out.

**Comment by sammael-s1** [comment]
Animation on switching workspaces is broken when using multiple screen setup. It was mentioned already. However suggestion to disable animation i gnome-tweaks was... not entirely satisfying. Than I came across this extension: https://extensions.gnome.org/extension/1328/disable-workspace-switch-animation/
This made my life good again. Cheers

**Comment by jsravn** [comment]
There's a PR in the fork to fix workspace animations. Now to wait for the fork to merge the PRs :joy:...

**Comment by gavr123456789** [comment]
So, can you write instructions for those who are not in the topic how to run paper wm in GNOME 41 now?

**Comment by cstich** [comment]
> So, can you write instructions for those who are not in the topic how to run paper wm in GNOME 41 now?

Don't the instructions for GNOME 40 (see above) still work?

**Comment by gavr123456789** [comment]
Ye, for everybody who not familiar with all of this:  
1) go https://github.com/PaperWM-community/PaperWM/tree/next-release and git clone / download  
2) put folder to .local/share/gnome-shell/extensions/
3) install.sh restart shell, turn on extension

**Comment by jsravn** [comment]
All I needed was the vertical overview plugin to fix workspace switching. No other extensions necessary with the fork.

**Comment by magthe** [comment]
@gavr123456789 so `next-release` is better than `develop` at the moment?

**Comment by jsravn** [comment]
Yes, especially since the prefs window works.

**Comment by paven** [comment]
The Orefs, do not work with my setup with next-release. Gnome 40.0.4, X11
Ubuntu.
\________
/  Patrik G

**Comment by wraithm** [comment]
I'm running the https://github.com/PaperWM-community/PaperWM/tree/next-release version. I've noticed that a handful of keyboard shortcuts don't work in my current set up with GNOME 40. Things like `Super-V` (look at notifications) and `` Super-` `` don't behave as expected.

Also, how do I get my custom `user.js` shortcuts and such working?

**Comment by MikulasVanousek** [comment]
Shortcuts don't work for me in vanilla gnome all the time. For example, right now, moving to the second desktop with super+2 stopped working. All other desktops (1..6) work fine. Sometimes different shortcuts don't work.

**Comment by MikulasVanousek** [comment]
> Ye, for everybody who not familiar with all of this:
> 
>     1. go https://github.com/PaperWM-community/PaperWM/tree/next-release and git clone / download
> 
>     2. put folder to .local/share/gnome-shell/extensions/
> 
>     3. install.sh restart shell, turn on extension
> 
> 
> Checked on GNOME 41.1 Arch Everything works except the switch between desktops by win + page up/down https://extensions.gnome.org/extension/1328/disable-workspace-switch-animation/ didnt help

I followed the steps and ended up getting a version error. 
![image](https://user-images.githubusercontent.com/33402194/151321508-07c14aa8-dc10-4a4c-928e-f2febbb838a0.png)

**Comment by magthe** [comment]
I got the broken shortcuts back to working by going into the ordinary Gnome settings and aggressively turning off shortcuts there.

**Comment by jsravn** [comment]
Yeah there is some issue with shortcuts, I noticed this too. I fixed it I think by resetting shortcuts and toggling the extension off/on again. Doesn't help though the shortcut reset crashes in gnome 41.

**Comment by ccope** [comment]
I'm using (abusing?) this discussion thread to document issues I'm finding with the soft-fork under Ubuntu 22.04/GNOME 41/Wayland: https://github.com/PaperWM-community/PaperWM/discussions/20

**Comment by oguzserbetci** [comment]
@MikulasVanousek I got an error as well, but it was because popos-shell was activated. After I turned it off and restarted gnome shell PaperWM worked.

**Comment by smichel17** [comment]
In the fork, there is code which:

- Adds support for gnome 40 and 41, but breaks compatibility with gnome 38 or earlier
- Fixes bugs or adds features, and does not affect compatibility
- Adds support for gnome 42, but breaks compatibility with gnome 41 or earlier

However, much of this code is scattered across a bunch of branches and PRs. The task now is to merge it all together and bring it upstream here.

This issue is very long, and the code to address it already all exists in the `master` branch of the fork, so I think I am going to merge that first (disregarding any additional bugfixes or features not yet included there), close this issue, and we can continue the discussion of getting gnome 42 work merged here in #409. If there are any other problems that pop up, we can open new issues here to track them.
